### ISSUE TITLE
Comparison with Yesql

### ISSUE THREAD

**Issue by ul** [layerware/hugsql#1]
It would be nice to highlight key differences with [Yesql](https://github.com/krisajenkins/yesql).

**Comment by csummers** [comment]
I agree.  I'll add a section in the README addressing Yesql, since many developers may be familiar with it.  Thanks!

**Comment by ul** [comment]
Thank you for your commitment in search of Graal of talking to DB servers. Projects like HugSQL and Yesql decomplect things a lot!

**Comment by csummers** [comment]
Released in 0.3.0 on the new documentation site: [hugsql.org] (http://hugsql.org)
