### ISSUE TITLE
Interned vars do not have :arglists metadata

### ISSUE THREAD

**Issue by ProjectFrank** [layerware/hugsql#100]
Variables interned by HugSQL do not include `:arglists` metadata. This metadata is useful for docstrings, as will as certain stubbing libraries that rely on it for arity checking (e.g. https://github.com/circleci/bond/). This seems easily fixable by adding hardcoded `:arglists` metadata that reflects what's shown on the [docs](https://www.hugsql.org/#using-def-db-fns):

```clojure
      [db]
      [db param-data]
      [db param-data options & command-options]
```

**Comment by j0ni** [comment]
Ahem #88 @ProjectFrank

**Comment by ProjectFrank** [comment]
Oops, closing
