### ISSUE TITLE
question about queries with multiple statements

### ISSUE THREAD

**Issue by little-dude** [layerware/hugsql#101]
Hi,

I tried the following:

```sql
-- :name delete-message!
-- :doc delete a message by id
-- :command :execute
-- :result: :affected
BEGIN;
-- ;;
DELETE FROM message_status WHERE message_status.message_id = :id;
-- ;;
DELETE FROM message WHERE message.id = :id;
-- ;;
COMMIT;
```

The message and status do get deleted when I call `delete-message!` but I have the following exception:

```
myapp.db.core=> (delete-message! {:id 4})
Execution error (PSQLException) at org.postgresql.jdbc.BatchResultHandler/handleCommandStatus (BatchResultHandler.java:92).
Too many update results were returned.
```

Is what I'm trying to do an anti-pattern? Or am I just using hugsql the wrong way? I know I could split these two `DELETE` and use `jdbc/with-db-transaction` to do a transaction but having the two delete in the same query seems simpler to me.

**Comment by csummers** [comment]
>  I know I could split these two `DELETE` and use `jdbc/with-db-transaction` to do a transaction but having the two delete in the same query seems simpler to me.

I splitting these up and putting into a transaction is the only way to do multiple statements right now.  I'm open to that not being the case in the future, but I'd need to see how the underlying libraries are handling multiple statements.

**Comment by mcbloch** [comment]
Is there any update on creating a syntax for combining queries without using `jdbc/with-db-transaction`?
