### ISSUE TITLE
How do you choose intervalstyle format for interval datatype in postgres ?

### ISSUE THREAD

**Issue by Zyxmn** [layerware/hugsql#102]
I would like fetch an interval datatype in a particular format . I cannot find a way to do this yet with hugsql. 

As shown in this doc http://www.postgresqltutorial.com/postgresql-interval/ , I need to run a `SET` to choose interval format before I do the `SELECT` like so .
```
SET intervalstyle = 'iso_8601';

SELECT
   INTERVAL '6 years 5 months 4 days 3 hours 2 minutes 1 second';
```

Also when fetching interval datatype in  `iso_8601` format (which seems to be the default format) , I get all the fields even if their value is zero .

For Example: If the interval value of a record in the database is 5 seconds.

hugsql output : P0Y0M0DT0H0M5.0S
psql output:  PT5S

Is it possible to ignore the zero value fields

**Comment by csummers** [comment]
Are you able to separate these into two HugSQL statements (which will generate 2 functions), and then execute them in a [transaction](https://www.hugsql.org/#using-transactions) to achieve the result you want?
