### ISSUE TITLE
Error on 0.5.0

### ISSUE THREAD

**Issue by kanwei** [layerware/hugsql#105]
```
Execution error (IllegalArgumentException) at hugsql.adapter/eval12891$fn$G (adapter.clj:3).
No implementation of method: :on-exception of protocol: #'hugsql.adapter/HugsqlAdapter found for class: hugsql.adapter.clojure_java_jdbc$hugsql_adapter_clojure_java_jdbc
```

**Comment by kanwei** [comment]
Using the conman library

**Comment by csummers** [comment]
I'll try to reproduce.

**Comment by csummers** [comment]
I was able to reproduce and found the issue.  A quick fix in 0.5.1 should be out very soon.

**Comment by csummers** [comment]
0.5.1 is released with a fix for this (I think).  Would you mind testing your project and reporting back.  Thanks!

**Comment by kanwei** [comment]
Works again, thanks very much!

**Comment by csummers** [comment]
Thank you for the quick reporting!
