### ISSUE TITLE
Example of options passed to SQL fns contain option not passed

### ISSUE THREAD

**Issue by Sardtok** [layerware/hugsql#107]
https://github.com/layerware/hugsql/blob/18f1fa72883cd64a22dd2252a12bbee331ca0ac5/docs/hugsql.org/index.html#L302

Is there any reason the adapter is not among the options that are documented here? I realize this is just an example of what options are passed, but should perhaps be removed if it's not actually available. Not a big issue, I got around the problem by creating adapter dependant views in migration scripts, instead of choosing system tables based on the adapter in queries.

**Comment by csummers** [comment]
@Sardtok Are you saying that these options are not working?

For example, passing the `:adapter` into your query function: 

```
(ns my-db-stuff
(:require [hugsql.core :as hugsql]
          [hugsql.adapter.next-jdbc :as next-adapter]))

(def db ;;a db-spec here)

(hugsql/def-db-fns "path/to/db.sql")

(my-query db {:id 1}
  {:adapter (next-adapter/hugsql-adapter-next-jdbc)})
```
From: https://www.hugsql.org/#adapter-setting

**Comment by Sardtok** [comment]
Ah, my bad. I had not dug down enough into our codebase to find how our adapter settings were used. They were Hikari adapter settings (i.e. a DB driver identifier), and I figured they were being made available to HugSQL. Obviously as the adapter docs explain, they are completely different adapter settings entirely.
