### ISSUE TITLE
Question about next.jdbc and update queries.

### ISSUE THREAD

**Issue by lukaszkorecki** [layerware/hugsql#109]
I have a simple update query:

```sql
-- :name  update-email* :!
update people
set email = :new-email where email = :old-email

```

The result of that query is:

```clojure
(update-email* connection {:old-email "test@test.com" :new-email "test2@test.com"})  
; => {:next.jdbc/update-count 1}
```

I'd like to somehow keep the old behavior and return `1` instead. 

I've checked the configuration options for next.jdbc and looks like it cannot be disabled there (understandable!). But, after checking out the adapter source - I found this line:

https://github.com/layerware/hugsql/blob/18f1fa72883cd64a22dd2252a12bbee331ca0ac5/hugsql-adapter-next-jdbc/src/hugsql/adapter/next_jdbc.clj#L29

So I'm not sure what's going on - is the definition of my query wrong? Or is it a bug? (unlikely!)

Extra info:

hugsql version: 0.5.1
next.jdbc 1.0.13
next.jdbc adapter: 0.5.1

**Comment by csummers** [comment]
Hi @lukaszkorecki,

Your query should specify the expected `:result`.  In this case, `:affected` or `:n` (for short):

```
-- :name  update-email* :! :n
update people
set email = :new-email where email = :old-email
```

See: https://www.hugsql.org/#result

**Comment by lukaszkorecki** [comment]
@csummers ahh, got it - I see it now - I've tried `:1` before and I was getting the same result. Indeed, switching to `:n` fixes it. Thank you 👍
