### ISSUE TITLE
Queries with reused parameter names don't play well with sqlvec

### ISSUE THREAD

**Issue by orestis** [layerware/hugsql#110]
I'm not sure if I'm doing something wrong or I'm misunderstanding how hugsql sqlvec is supposed to work.

My use case is to automatically EXPLAIN ANALYZE some slow queries. To do that, I have two options:

1. Add the EXPLAIN ANALYZE as a conditional expression
2. Get the SQL query as returned by sqlvec and prepend EXPLAIN ANALYZE to it.

But since I'm reusing some parameter names, the params of the sql vec only returns one value.

Example (contrived) query:

```
SELECT * from foo where foo.x = :fred AND foo.y = :fred
```

Running this as an actual function produces the correct results, but the sql vec flavour wll return this (say the params are `{:fred "1"}`:

```
["SELECT * from foo where foo.x = :? AND foo.y = ?"
 "1"]
```

Meaning that JDBC will complain about missing parameters.

**Comment by csummers** [comment]
Hmm...I'm not seeing the behavior you're describing.  Can you provide a full example demonstrating the issue?

```clj
user=> (require '[hugsql.core :as hugsql])
nil
user=> (hugsql/def-sqlvec-fns-from-string "-- :name test\nselect * from foo where x = :a and y = :a")
nil
user=> (test-sqlvec {:a 1})
["select * from foo where x = ? and y = ?" 1 1]
```

**Comment by orestis** [comment]
Whoops! You're right, I got confused about the sqlvec format:

I was doing:

```
(let [[sql params] (test-sqlvec {:a 1})]
 [sql params])
```

Where I should be doing:

```
(let [[sql & params] (test-sqlvec {:a 1})]
 [sql params])
```

Sorry for the trouble!

**Comment by csummers** [comment]
Great!  Happy to help! :smile:
