### ISSUE TITLE
Add support for next.jdbc.sql/insert-multi!

### ISSUE THREAD

**Issue by ILoveHubGit** [layerware/hugsql#118]
Can you please add support for the `insert-multi!` function of the library `next.jdbc` this makes it possible to insert multiple records at once to a database. In this real-time world a must to have :-)

**Comment by csummers** [comment]
HugSQL already supports multiple inserts with the Tuple List parameter type: https://www.hugsql.org/#param-tuple-list as long as your database supports tuple syntax.
