### ISSUE TITLE
Explore composable features

### ISSUE THREAD

**Issue by csummers** [layerware/hugsql#12]
This is a catch-all ticket for exploring features making HugSQL more composable.  All ideas welcome!

**Comment by csummers** [comment]
We might could have SQL snippets identified in the SQL file with a `-- :snippet` special comment (as opposed to `-- :name`), or using some inline snippet notation within a regular query.  A Snippet Parameter Type would integrate snippet function results passed as parameter data into the regular query functions.

**Comment by yatesco** [comment]
Hey, that is great. Ideally I would have one `snippet` for 'restrict by X' another for 'restrict by Y', 'restrict by Z' etc. and a fully formed query. I could then 'attach' the relevant 'snippets' to the query based on the runtime data. If they only restrict by 'Y' then I 'attach' the 'restrict by X' snippet to the query?

For clarity - in my current Honey SQL implementation I have something like the following:

```
(defn restrict-by-x [filter m] (if (:x filter) (add-where m [:= :x (:x filter)]) m)
(defn restrict-by-y [filter m] (if (:y filter) (add-where m [:= :y (:y filter)]) m)
(defn restrict-by-z [filter m] (if (:z filter) (add-where m [:= :z (:z filter)]) m)

(defn filter->sql [filter] 
  (-> (base-query filter)
        (restrict-by-x filter)
        (restrict-by-y filter)
        (restrict-by-z filter))
```

No, of course I don't really do that, but I hope it clarifies the intent :-)

**Comment by ohlo** [comment]
+1 for snippet

**Comment by csummers** [comment]
As of 0.4.0, we have [Clojure Expressions](http://www.hugsql.org/#using-expressions) and [Snippets](http://www.hugsql.org/#using-snippets) to compose your SQL.  Check'em out!

**Comment by xurelo** [comment]
Hello guys,

I'm not sure how the snippets work:

-- :snip test-snip
select * from store.contents

-- :name test-contents :? :*
:snip:test-snip limit 10

The following error is shown: Parameter Mismatch: :test-snip parameter data not found

The sql queries are parsed  by means of: hugsql/map-of-db-fns-from-string.

I am pretty sure I am missing something, but I do not know what it is.

**Comment by csummers** [comment]
Snippets create functions in your namespace that you must provide in your larger query function's parameters:

```clj
(test-contents db {:test-snip (test-snip)}
```

Read through https://www.hugsql.org/#using-snippets for more, and check out https://www.hugsql.org/#using-expressions for runtime composability.

**Comment by xurelo** [comment]
Thanks for the quick answer, but I can't get it working.
Should I do any ns-resolve with the name of the snippet in order to resolve it?  I have tried (ns-resolve 'mynamespace (symbol "test-snip")) but I get a nil.
