### ISSUE TITLE
HugSql fails during AOT compilation with depstar

### ISSUE THREAD

**Issue by kelvinqian00** [layerware/hugsql#126]
I am using HugSql in a project that will require AOT compilation. To init our HugSql functions, we have a `record` namespace which contains calls to the `def-db-fns` macro (to define functions that will be used in a record in that same namespace). We pass to `def-db-fns` a path to a .sql file; as this is a closed-source project, we ideally want to not include those .sql files in the final release, so we use depstar's `:exclude` feature to exclude .sql (and .clj) files from our jars.

Here is the approximate file structure of our project:

```
+ h2/h2/
+--+ sql/
      +--+ ddl.sql
      +--+ [more .sql files]
+--+ main.clj
+--+ record.clj
+ main/
+ test/
```

In `record.clj`, we call the following:
```clojure
(ns h2.record
  (:require [hugsql.core :as hugsql] [other requires]))

(hugsql/def-db-fns "h2/sql/ddl.sql")
; more calls to def-db-fns
```

In `deps.edn`, we define multiple aliases for each DBMS we use (since our project aims to be utilized with multiple DB types):
```clojure
:aliases
{:db-h2
 {:extra-paths ["src/h2"]
  :extra-deps  {com.h2database/h2 {:mvn/version "1.4.200"}}}
 ; more DB aliases
 :uberjar
 {:replace-deps {com.github.seancorfield/depstar {:mvn/version "2.0.216"}}
  :exec-fn hf.depstar/uberjar
  :exec-args {:aot true}}}
```

However, when performing AOT compilation using depstar, this fails.

```
% clojure -X:uberjar :jar foo.jar :aliases '[:db-h2]' :exclude '["^lrsql.*clj$" "^lrsql.*sql$"]' :main-class h2.main
[main] INFO hf.depstar.aot - Compiling h2.main ...
[main] INFO hf.depstar.uberjar - Building uber jar: foo.jar

% java -jar foo.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at clojure.lang.RT.classForName(RT.java:2212)
    at clojure.lang.RT.classForName(RT.java:2221)
    [a bunch more calls]
Caused by: clojure.lang.ExceptionInfo: Can not read file: h2/sql/ddl.sql {}
    at hugsql.core$parsed_defs_from_file.invokeStatic(core.clj:60)
    at hugsql.core$parsed_defs_from_file.invoke(core.clj:48)
    at h2.record$fn__2520.invokeStatic(record.clj:8)
    at h2.record$fn__2520.invoke(record.clj:8)
    at h2.record__init.load(Unknown Source)
    at h2.record__init.<clinit>(Unknown Source)
    ... 70 more
```

The reason for this is that `def-db-fns` tries to read `ddl.sql` _at runtime_, rather than during compile time. This is despite the HugSql documentation saying that DB functions are defined at compile time, so we concluded that this issue must be a bug.

As a "temporary" patch, we wrote our own version of `def-db-fns` that would read the .sql file during compile time:
```clojure
(defmacro custom-def-db-fns
  ([file options]
   (let [parsed-defs# (parsed-defs-from-file file)]
    `(doseq [~'pdef ~parsed-defs#]
       (validate-parsed-def! ~'pdef)
       (compile-exprs ~'pdef)
       (if (snippet-pdef? ~'pdef)
         (intern-sqlvec-fn ~'pdef ~options)
         (intern-db-fn ~'pdef ~options))))))
```
Ideally, all aspects of defining DB functions (including `validate-parsed-def!`, `compile-exprs`, etc.) should be done at compile time, but just reading the .sql files at compile time instead of runtime was enough to fix the issue for us.

**Comment by csummers** [comment]
@kelvinqian00 Release `0.5.2` (and quick followup `0.5.3`) fixes hugsql-defined functions to be at def'd at compile time.  Please let me know if this fixes it for you.  Thanks!

**Comment by kelvinqian00** [comment]
Thanks! I'll check it out and let you know if it works.

**Comment by kelvinqian00** [comment]
Indeed it does work! (Plus the conversion from using macros to regular functions cleans up the core code.)

**Comment by jngbng** [comment]
Does it work well with leiningen?
I am using leiningen and still have the same problem. Uberjar with option 'aot all & omit-source' still throws 'Can not read file' exception.
Test project: https://github.com/jngbng/hugsql_aot
