### ISSUE TITLE
Switch to newer groupId of next.jdbc dependency in hugsql-adapter-next-jdbc

### ISSUE THREAD

**Issue by dmarjenburgh** [layerware/hugsql#127]
next.jdbc was moved from the groupId `seancorfield` to `com.github.seancorfield` since release 1.1.643.
I encountered some issue having the following in my deps.edn:
```clj
com.github.seancorfield/next.jdbc {:mvn/version "1.2.674"}
com.layerware/hugsql {:mvn/version "0.5.1"}
com.layerware/hugsql-adapter-next-jdbc {:mvn/version "0.5.1"}
```
Two versions of the next.jdbc jar were in my classpath. This required updating my adapter dependency to:
```clj
com.layerware/hugsql-adapter-next-jdbc {:mvn/version "0.5.1"
                                        :exclusions [seancorfield/next.jdbc]}
```

Switching to the newer groupId requires users of hugsql-adapter-next-jdbc to also switch to the newer `next.jdbc` groupId (but they would be updating their deps anyway).

Another solution could be to *not* include next.jdbc with the adapter at all and use it as a peer dependency.

**Comment by csummers** [comment]
@dmarjenburgh Release in `0.5.2` (and quick followup `0.5.3`). Thanks!
