### ISSUE TITLE
Babashka support

### ISSUE THREAD

**Issue by jprudent** [layerware/hugsql#133]
Hello! 

I tried to use Hugsql with Babashka but had a crash. 

I just want to ask if someone had any success using hugsql with babashka ?

---

And thanks for Hugsql, it's the best UX to work with SQL in Clojure !

**Comment by ieugen** [comment]
This might be useful https://github.com/babashka/babashka/blob/master/doc/dev.md#jdbc .

**Comment by jprudent** [comment]
It was an old question of me, I don't remember if if I got there but I don't expect answer anymore. Anyway, I'm closing it.
