### ISSUE TITLE
Using classpath resource sql functions breaks cider

### ISSUE THREAD

**Issue by gtrak** [layerware/hugsql#137]
Getting an issue like:
![image](https://user-images.githubusercontent.com/852666/160480785-5910899c-66f8-491f-b7b5-8da49c311583.png)

when eldoc is called on a generated DB function from a sql file passed in via clojure.java.io/resource (a URL). I'm suspicious of https://github.com/layerware/hugsql/blob/master/hugsql-core/src/hugsql/core.clj#L39 returning whatever is passed into it, and that making it into the var metadata later. 

I think this is probably responsible, since other var metadata is always a string:
```
the-namespace> (meta #'the-function)
{:doc ""
 :command :?,
 :result :*,
 :file
 #object[java.net.URL 0x7b4e1114 "file://the-file-path"]
 :line 101,
 :arglists ([db] [db params] [db params options & command-options]),
 :name the-name,
 :ns #namespace[the-namespace]}
```

According to clojure docs it should always be a string like `clojure/core.clj`: https://clojure.org/reference/special_forms#Special%20Forms--%28def%20symbol%20init?%29

Cider seems to be able to handle a file URI just fine, so you might not need to relativize it:

`(alter-meta! #'the-function (fn [m] (update m :file str)))` unbreaks it again.

Consider just doing `{:file (str file)}` on line 52?

**Comment by gtrak** [comment]
I should also note that we are using io/resource because hugsql broke in an uberjar, since the files no longer exist. I think if #126 were fixed we would not have needed io/resource.

**Comment by csummers** [comment]
@gtrak Release `0.5.2` (and quick followup `0.5.3`) contain fixes for the compile-time bug (https://github.com/layerware/hugsql/issues/126) and your suggested fix of stringifying the file.  Please let me know if this works for you.  Thanks!
