### ISSUE TITLE
strange key with jsonb

### ISSUE THREAD

**Issue by Xylon2** [layerware/hugsql#140]
First off, I'd like to thank the developers for this elegant framework.

I'm wanting to store JSON in postgres using the jsonb type. As an experiment, make the tables using psql:
```
create table playground (id serial not null primary key, imagemeta jsonb)
insert into playground (imagemeta) values ('{"bar": "baz", "balance": 7.77, "active":false}');
```

Now add the following in my HugSQL file:
```
-- :name jsonbtest :? :*
-- :doc testing jsonb with test table
select id, imagemeta->:field from playground;
```

Now in clojure repl:
```
> (db/jsonbtest {:field "balance"})
[{:id 1, :?column? 7.77}]
```

Why does the map I get back have such a strange key? Is this a bug?

**Comment by csummers** [comment]
You're using a [value parameter type](https://www.hugsql.org/hugsql-in-detail/parameter-types/sql-value-parameters) (the default) to specify an identifier.  In SQL, a column name--or a jsonb path as you have here-- is an identifier.  So, you need to use an [identifier parameter type](https://www.hugsql.org/hugsql-in-detail/parameter-types/sql-identifier-parameters).

The trick will be that the entire json path is the identifier (i.e., `imagemeta->balance` vs only `balance`), so you will need to pass the full path in.

Alternatively, you could use a [raw parameter type](https://www.hugsql.org/hugsql-in-detail/parameter-types/sql-raw-parameters), but please make sure to validate and sanitize any user input.

**Comment by csummers** [comment]
Scratch everything from my last/deleted comment.  That's the value that PG returns directly for a json path unless you give it an alias:

```sql
playground=# select id, imagemeta->'balance' from playground;
 id | ?column? 
----+----------
  1 | 7.77
(1 row)

playground=# select id, imagemeta->'balance' as balance from playground;
 id | balance 
----+---------
  1 | 7.77
(1 row)
```

**Comment by csummers** [comment]
So, if you want to specify the field as an identifier parameter type in the column alias, you could do:

```sql
select id, imagemeta->:field as :i:field from playground
```

**Comment by Xylon2** [comment]
Ah, thankyou! So not a bug at-all then.
