### ISSUE TITLE
Cannot look up by UUID

### ISSUE THREAD

**Issue by himat** [layerware/hugsql#142]
Hi, I have a table with a UUID column (called `external_id`) and I'm trying to write a query to look up a row by UUID but it's not working and fails with 

```
clojure.lang.ExceptionInfo: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 42 {:query-id :get-business-for-external-id}
        at conman.core$try_query$fn__15886$fn__15887.invoke(core.clj:34)
```

Here's the hugsql function
```
-- :name get-business-for-external-id :? :1
-- :doc retrieves a record given the external id
SELECT * FROM business
WHERE external_id = :external_id
```

I even tried doing `WHERE external_id = :external_id::uuid` but that didn't work either

**Comment by csummers** [comment]
`WHERE external_id = :external_id::uuid` is the solution to this issue.  Are you sure this didn't work?

**Comment by himat** [comment]
It worked now actually. I think I maybe just confused myself with another error that happened after I did the fix.
