### ISSUE TITLE
Migrations DSL

### ISSUE THREAD

**Issue by Dimitrije-Ciric** [layerware/hugsql#148]
I am choosing the library for DAL. Hugsql is the best option. 
After reading the docs, I have not found a tool to automatize DDL query execution(I have to execute them by hand). I may be missing something.

I was searching for something like [this](https://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html). I think this feature would not oppose hugsql philosophy, it would allow handier DDL execution.

**Comment by csummers** [comment]
@Dimitrije-Ciric There are already several good migration libraries for Clojure.  Here are two:

- https://github.com/weavejester/ragtime
- https://github.com/yogthos/migratus
