### ISSUE TITLE
Non positional insert-multi

### ISSUE THREAD

**Issue by AndreaCrotti** [layerware/hugsql#150]
From all the examples I found
https://www.hugsql.org/hugsql-in-detail/parameter-types/sql-tuple-list-parameters/
it looks like you need to always pass positional arguments to insert-multi, it be nice to avoid since that's quite brittle, and if could break easily.
Is there any way to do something like

```(tuple-param-list-sqlvec {:people [{:id 1, :name "bob"]})```

for example?

**Comment by csummers** [comment]
In this case, what would you envision the parameter in the SQL looking like?

**Comment by AndreaCrotti** [comment]
yeah I guess the complicated thing is that the `INSERT INTO` will still have the fields hardcode so it might not work, unless we can just generate the whole statement.
I was more used to honeysql and next.jdbc https://cljdoc.org/d/com.github.seancorfield/next.jdbc/1.3.939/api/next.jdbc.sql#insert-multi!
where you can normally just pass hashmaps, but maybe this can't really work in hugsql given how it works.

**Comment by AndreaCrotti** [comment]
Well unless maybe there could be some syntax like
`INSERT INTO some.table :hashmaps**`

which expands both the fields and all the values, but maybe that's a crazy idea

**Comment by csummers** [comment]
I think a very reasonable thing to do here, as suggested on the [page](https://www.hugsql.org/hugsql-in-detail/parameter-types/sql-tuple-list-parameters/), is to use a transaction and loop over regular insert statements.

> CAUTION
BATCH INSERTS: It should be noted that Tuple List Parameter support is only support for SQL INSERT...VALUES (...),(...),(...) syntax. This is appropriate for small-ish multi-record inserts. However, this is different than large batch support. The underlying JDBC driver for your database has a limit to the size of the SQL and the number of allowed bind parameters. If you are doing large batch inserts, you should map or doseq over your HugSQL-generated insert function within a [transaction](https://www.hugsql.org/using-hugsql/transactions).

**Comment by csummers** [comment]
I agree!  There's nothing wrong with using the underlying library directly for this.
