### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by Skinney** [layerware/hugsql#2]
Problems I stumbled onto when trying out this library:

Placing this in my project.clj file gave me an error: `[com.layerware/hugsql "0.2.0"]`
The error was something about not finding `hugsql-core "0.1.0"` in clojars if I remember correctly.

You should also note that hugsql uses io/resource to find sql files. My app crashed and I had no idea why, removing "resources" from the provided path-string solved the issue.

You should also probably have at least one execute (:!) example in the README. All your examples are currently select statements.

Other than that, great stuff!

**Comment by csummers** [comment]
The hugsql-core 0.1.0 is definitely a bug leftover from a quick roll-out of 0.1.1.  Thanks for the catch.

I'll look into the other issues.  I might circle back for more detail on the io/resource issue.  I agree about more examples with :execute.

Thanks!

**Comment by csummers** [comment]
Fixed in 0.2.1
