### ISSUE TITLE
Snake case and Kebab case

### ISSUE THREAD

**Issue by simax** [layerware/hugsql#21]
One common problem is SQL column names tend to be snake_case and clojure map keywords tend to be kebab-case. Is there a way to automatically change them on the way in and out of sql statements. Pupeno is using quite a neat trick here https://carouselapps.com/2015/10/23/automatically-converting-case-between-sql-and-clojure/ with conman and yesql but it'd be nice if this could happen out of the box. Is this possible or any plans for anything like this?

**Comment by csummers** [comment]
@simax Good question.  We don't have built-in support in HugSQL for snake/kebab/camel conversion, but we do have some tools enabling you to easily hook into the returned results in the form of the `hugsql.core/hugsql-result-fn` multi-method.

You can create your own result types OR override the existing ones.  For example, here's how you would override the result type for `:1`, which returns a single hashmap.  You would need to override all of the result types that might contain hashmaps with keys to be converted.  So, for builtin result types, this would include `:1`, `:one`, `:*`, and `:many`.

``` clj
(defn result-one-snake->kebab
  [this result options]
  (->> (hugsql.adapter/result-one this result options)
       (csk-extras/transform-keys csk/->kebab-case-keyword)))

(defmethod hugsql.core/hugsql-result-fn :1 [sym] 'hugsql.core-test/result-one-snake->kebab)
```

Notice that the multi-method points to a quoted, fully-namespace-qualified function (this one I tested out briefly in my test namespace).  That's the answer for results coming back from the database.

For identifiers (table names and column names), you can do a similar process by overriding the `hugsql.parameters/apply-hugsql-param` multi-method for identifier parameter types: `:i`, `:identifier`, `:i*`, and `:identifier*`.

At this point, I think I'd like to let these hooks be the "solution" for this problem.  If I get a significant amount of requests for this feature, I would look at building it in.

**Comment by simax** [comment]
Interesting. I'll have a play around with your suggestions, they sound promising. Thanks for the advice and hugsql.

**Comment by csummers** [comment]
You're welcome!  Let me know if you run into any further issues or questions.  I very much want to make HugSQL a robust, practical solution for lots of use cases.

**Comment by alndvz** [comment]
I've taken the advice above, however when passing in kebab case params and using snake params in my SQL hugsql.core/validate-parameters! throws an exception. Is there a way to modify the params before they got to this function? It seems the apply-hugsql-param multimethod is executed after this validation function. Am I missing something?

**Comment by jgrodziski** [comment]
I've put a very first draft of a core.async version of your function for those using postgres.async with hugsql adapter:
https://gist.github.com/jgrodziski/d1af3999c82d048f208698ae4c7ab819

**Comment by nackjicholson** [comment]
https://luminusweb.com/docs/database.html#massaging_key_names_from_sql_to_clojure_style

This section of the luminus documentation has a description of how to convert keys. Pasting here because I ran across it, but I think I'm going to use `:snake_case` keywords everywhere.
