### ISSUE TITLE
"contains? not supported on type: java.util.UUID" error when using a list/vector on the params map

### ISSUE THREAD

**Issue by rcanepa** [layerware/hugsql#25]
Hey,

I am working on a small piece of code to insert rows in a table. The SQL is very simple:
````
-- :name insert-contact :? :1
-- :doc Insert a contact record.
INSERT INTO contacts
  (:i*:fields)
VALUES
  (:v*:values)
RETURNING id;
````
As you can see, `fields` is a keyword which contains a list of strings (the name of some table fields), and `values` is another keyword which contains values (integers, strings, uuid, etc.) for those table fields.

On top of that, I have a function which call this SQL with a map with two keywords: fields and values. See here:
````
(s/defn create-contact :- {s/Keyword s/Uuid}
  [db :- ConnectionMap
   contact :- schemas/Contact]
  (let [contact (select-keys contact schemas/contact-db-fields)
        sql-args {:fields (map name (keys contact))
                  :values (vals contact)}]
    new-contact (execute! db :insert-contact sql-args)))
````
If I print the sql-args (params) map I get something like this:
```
{:fields (owner_id address email first_name created_by_id extra_service_data organization_name phone identifier last_name), 
 :values (#uuid "57dce206-acc4-43a4-849c-9491bda0cd22" abc abc@abc.cl ABC #uuid "57dce206-acc4-43a4-849c-9491bda0cd22"  ABC CORP 123123123 1 ABC)}
```
However, when I execute the function with those parameters, I get this error:
````
#error {
 :cause "contains? not supported on type: java.util.UUID"
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.lang.IllegalArgumentException: contains? not supported on type: java.util.UUID, compiling:(scv2backend/models/contacts_test.clj:10:1)"
   :at [clojure.lang.Compiler load "Compiler.java" 7391]}
  {:type java.lang.IllegalArgumentException
   :message "contains? not supported on type: java.util.UUID"
   :at [clojure.lang.RT contains "RT.java" 814]}]
 :trace
 [[clojure.lang.RT contains "RT.java" 814]
  [clojure.core$contains_QMARK_ invokeStatic "core.clj" 1443]
  [clojure.core$contains_QMARK_ invoke "core.clj" 1435]
  [hugsql.core$validate_parameters_BANG_ invokeStatic "core.clj" 60]
  [hugsql.core$validate_parameters_BANG_ invoke "core.clj" 55]
  [hugsql.core$prepare_sql invokeStatic "core.clj" 172]
  [hugsql.core$prepare_sql invoke "core.clj" 160]
  [hugsql.core$db_fn_STAR_$y__10617 doInvoke "core.clj" 437]
  [clojure.lang.RestFn invoke "RestFn.java" 445]
  [hugsql.core$db_fn_STAR_$y__10617 invoke "core.clj" 428]
  [scv2backend.models.common$eval47760$executeQuery__47765$fn__47766 invoke "common.clj" 17]
  [scv2backend.models.common$eval47760$executeQuery__47765 invoke "common.clj" 12]
````
So, I am suspecting that there is a problem in the `hugsql.core$validate_parameters` function when it has to deal with a sequence which contains UUID values.

Also, If I remove the UUID fields, I got a PostgreSQL exception (violation of a not-null constraint), so I guess in that case the query is being executed.

**Comment by csummers** [comment]
That is strange.  `contains?` should only be accessing the params hashmap, not the actual value for the key it's looking for.

Where does your `execute?` function come from?  What does it look like?

**Comment by rcanepa** [comment]
First, I define `queries` which contains a map with all database functions:
````
(def queries
  (hugsql/map-of-db-fns "sql/events.sql"))
````
Then, I use the  `executeQuery` function as a wrapper of this piece of code `((-> queries query :fn) db args)`:
````
;; executeQuery comes from another namespace
(s/defn executeQuery
  [queries :- {s/Keyword s/Any}
   db :- ConnectionMap
   query :- s/Keyword
   args :- {s/Keyword s/Any}]
  ((-> queries query :fn) db args))
````
And `execute!` is just `executeQuery` curried (with the queries):
````
(def execute! (partial executeQuery queries))
````

I will go back to test on version 0.4 because I am pretty sure it was working before. Give me a couple of minutes.

**Comment by rcanepa** [comment]
Nevermind, I forgot that map-of-db-fns was added on version 0.4.1.

**Comment by rcanepa** [comment]
Curtis, I am not having this issue with version 0.4.1.

**Comment by csummers** [comment]
I'm having trouble duplicating your issue:

``` clj
user=> (require '[hugsql.core :as hugsql])
nil
user=> (hugsql/sqlvec "insert into test (:i*:fields) values (:v*:values)" {:fields ["id","uuid","name"] :values [1 (java.util.UUID/randomUUID) "Bo"]})
["insert into test ( id, uuid, name ) values ( ?,?,? )" 1 #uuid "dd09cde2-8966-413d-b756-c1dd328e2002" "Bo"]
```

**Comment by rcanepa** [comment]
Ok. Let me double check that if change to version 0.4.2 without touching anything it will break again.

**Comment by rcanepa** [comment]
Curtis, now I am a bit confused. For some reason, moving back to version 0.4.1 and then up to 0.4.2 solved the problem. In between I executed `lein clean`, could be related to that? 

Anyway, thanks for you time!

**Comment by csummers** [comment]
Maybe?  I've had to do a few `lein clean` in my time to fix strange behavior.  Glad you worked it out.  I'm glad to see you and others using HugSQL in depth.  I like how you're using `map-of-db-fns` and Schema together.
