### ISSUE TITLE
Identify missing query parameters by name (like Yesql)

### ISSUE THREAD

**Issue by kg4lod** [layerware/hugsql#29]
#### HUGSQL: 

`...is missing a required parameter.`

is not nearly as useful as:

#### YESQL:

```
java.lang.AssertionError: Assert failed: Query argument mismatch.
Expected keys: (:id)
Actual keys: 
Missing keys: (:id)
```

**Comment by csummers** [comment]
@kg4lod I'm not exactly sure what you are referring to.  HugSQL's parameter mismatch error looks like this:

```
(is (thrown-with-msg? ExceptionInfo
                              #"Parameter Mismatch: :id parameter data not found."
                              (one-value-param-sqlvec {:x 1})))
```

So, the parameter name is given to you in the error message.
Are you seeing different behavior, and can you provide an example of that behavior?

Thanks!

**Comment by csummers** [comment]
Is it possible that you are using HugSQL with [Luminus/conman](https://github.com/luminus-framework/conman)?  I did find a reference to "is missing a required parameter" in [this post regarding mount.core.DeferrableState](https://forums.pragprog.com/forums/387/topics/14104).  If that's not it, I'm happy to help track down the issue if you provide an example or more of the stack trace.  Thanks!

**Comment by kg4lod** [comment]
Thank you for the reply! I'll investigate today and report back. Apologies if I merely missed something.

**Comment by kg4lod** [comment]
I can confirm. I am now seeing this message:

`clojure.lang.ExceptionInfo: Parameter Mismatch: :id parameter data not found.`

Apologies for the errant issue.

**Comment by csummers** [comment]
No problem!  Glad you figured it out.

**Comment by kg4lod** [comment]
Actually what was going on is that I forgot (in only one place) to add the database connection as the second parameter. The error is actually being reported by JDBC as it looks for keys for the connection in my parameter data hashmap. Perhaps a clearer error message would help here since, I suspect, it is a common problem for people coming from Yesql-like libraries.
