### ISSUE TITLE
column name escaping

### ISSUE THREAD

**Issue by yogthos** [layerware/hugsql#31]
Ran into a funny one here. Postgres has some reserved keywords like `randomNumber`, so if you name a column that, then it won't be found. With plain clojure.java.jdbc you can escape it like this:

```clojure
(jdbc/update!
    db
    :world
    {"\"randomNumber\"" randomNumber}
    ["id = ?" id])
```

but it won't work with HugSQL:

```sql
-- :name update-world<! :<!
-- update an existing world record
UPDATE world
SET "randomNumber" = :randomNumber
WHERE id = :id
RETURNING id
```

I'm guessing the quotes don't end up being protected when the query is read.

**Comment by csummers** [comment]
Hmm.  Are you saying HugSQL is not leaving your double-quotes alone?  I'm not seeing that:

``` clj
=> (hugsql/sqlvec "update world set \"randomNumber\" = :randomNumber where id = :id returning id" {:randomNumber 5 :id 1})
["update world set \"randomNumber\" = ? where id = ? returning id" 5 1]
```

Do you have an error message to look at?

**Comment by yogthos** [comment]
hmm, might have to dig into this further. I was updating Luminus framework benchmarks [here](https://github.com/yogthos/FrameworkBenchmarks/commit/b8a1ec67779cc3306723bf33e210661dc7b07c7d), and got this error. [`org.postgresql.util.PSQLException: ERROR: column "randomNumber" of relation "world" does not exist`](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/116677879). However, doing it the other way seems to work.

**Comment by csummers** [comment]
These queries all work for me on postgresql in my test suite: 

```sql
-- :name create-world :!
create table world (
 id int,
 "randomNumber" int
)

-- :name drop-world :!
drop table if exists world

-- :name insert-world<! :<!
insert into world (id, "randomNumber")
values (:id, :randomNumber)
returning id

-- :name update-world<! :<!
-- update an existing world record
UPDATE world
SET "randomNumber" = :randomNumber
WHERE id = :id
RETURNING id
```

```clj
(testing "possible double-quote bug"
        (when (= db-name :postgresql)
          (= [0] (drop-world db))
          (= [0] (create-world db))
          (= [{:id 1}] (insert-world<! db {:id 1 :randomNumber 5}))
          (= [{:id 1}] (update-world<! db {:id 1 :randomNumber 42}))))
```

**Comment by yogthos** [comment]
Hmm, yeah that's odd. I just tried this on my machine at home and it works fine. When I tried it on a different machine earlier I got the same error as travis. Perhaps it's something to do with the version PG itself.

**Comment by yogthos** [comment]
Oh I think I figured it out. The query returns a `randomworld` key that's lower case. However, I was looking for the `randomWorld` key when updating. Nothing to do with HugSQL. :)
