### ISSUE TITLE
Question: Trying to use HugSQL with Apache Drill

### ISSUE THREAD

**Issue by spacepluk** [layerware/hugsql#34]
I'm new to HugSQL and I'm trying this simple query with Apache Drill:

```sql
-- :name test-query :? :*
select :test as test from (values (1))
```
```clojure
(test-query db {:test "test"})
```

This throws an exception:

```
java.sql.SQLFeatureNotSupportedException: Prepared-statement dynamic parameters are not supported.
```

Is there any easy way to workaround [this limitation in Drill](https://github.com/apache/drill/blob/a0be3ae0a5a69634be98cc517bcc31c11ffec91d/exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillPreparedStatementImpl.java#L92)?  Or maybe I'm doing something wrong :?

**Comment by csummers** [comment]
It looks like you're trying to use a [value parameter](http://www.hugsql.org/#param-value) where an [identifier parameter](http://www.hugsql.org/#param-identifier) should be.  When you don't specify the HugSQL [parameter type](http://www.hugsql.org/#param-types), it defaults to a value parameter, which is going defer parameter replacement to the underlying library.  So, what's happening here is that your effective SQL statement (sqlvec) will look like this to Apache Drill, which it apparently doesn't support bind parameters:

``` clj
["select ? as test from (values (1))" "test"]
```

You should use an identifier parameter type for column names with an `:identifier` or `:i` preceding your parameter name:

``` sql
-- :name test-query :? :*
select :i:test as test from (values (1))
```

which should result in the following sql (assuming you are not setting HugSQL `:quoting` option):

``` clj
["select test as test from (values (1))"]
```

The lack of Apache Drill's support for prepared statement parameter binding will likely be the next head scratcher when trying to query with where clause conditions.  You can get around this by using HugSQL's raw/keyword sql parameters, but I would caution using that for any user-provided values.

**Comment by spacepluk** [comment]
Thanks for the detailed explanation :)
I think I can use the raw sql parameters for now since I don't need sql-injection protection for this.
