### ISSUE TITLE
Bug? No space between clojure and sql snippet

### ISSUE THREAD

**Issue by sthomp** [layerware/hugsql#37]
I have the following SQL:

```
-- :snip my-join
JOIN users U on U.id = F.user_id

-- :snip my-where
WHERE U.id = 1

-- :name all-characters :? :*
-- :doc Get all characters
select * from first_table F
--~ (when (:join-table params) ":snip:join-table")
:snip:where-clause
```

And the following clojure:

```
(all-characters-sqlvec
  {:join-table (my-join)
   :where-clause (my-where)})
=> ["select * from first_table F  JOIN users U on U.id = F.user_idWHERE U.id = 1"]
```

Notice that there is no space before the `WHERE`.

It seems if you have a clojure snippet followed by a sql snippet theres no space in between them.

**Comment by sthomp** [comment]
I'm able to get this working if I change the sql query to:

```
-- :name all-characters :? :*
-- :doc Get all characters
select * from first_table F
--~ (when (:join-table params) ":snip:join-table")
--~ (when (:where-clause params) ":snip:where-clause")
```

**Comment by csummers** [comment]
Definitely looks like a bug.  I'll hunt it down.  Thanks for the report.

**Comment by csummers** [comment]
Found it.  The parser was eating trailing newlines for Clojure expressions.  This will roll out in the next release, which is likely to be today.

**Comment by csummers** [comment]
This is released in 0.4.6.  Please confirm that it fixes the issue for you.  Thanks!

**Comment by sthomp** [comment]
Great. Ill give this a shot on Monday. Thanks!

**Comment by sthomp** [comment]
Seems to be working now. Thanks!
