### ISSUE TITLE
Deprecation warnings in latest c.j.jdbc

### ISSUE THREAD

**Issue by kanwei** [layerware/hugsql#38]
DEPRECATED: unrolled sql / param groups in db-do-prepared-return-keys

**Comment by csummers** [comment]
I'm aware of the deprecation warnings to the current 0.5.7,8 in clojure.java.jdbc and the upcoming 0.6.x, which will remove all of these deprecation warnings.  It does appear that HugSQL will be affected, but HugSQL's clojure.java.jdbc dependency is currently set at 0.4.2.

I'm actually waiting a bit to let the dust settle on all of the clojure.java.jdbc changes before changing HugSQL's dependency.  I will likely make the jump straight to clojure.java.jdbc 0.6.x with the corresponding changes.  I expect this may be a week or two from now.

**Comment by kanwei** [comment]
That's great! Still loving the simplicity of the library and timeliness of updates :)

**Comment by csummers** [comment]
I just released 0.4.7 that fixes the clojure.java.jdbc deprecation warnings.  The HugSQL clojure.java.jdbc adapter's dependency is specifically set to the latest stable 0.5.8, but these changes in HugSQL 0.4.7 should allow you to specify and use HugSQL without issue in the upcoming clojure.java.jdbc 0.6.x.
