### ISSUE TITLE
Missing :name -> NullPointerException

### ISSUE THREAD

**Issue by AdamFrey** [layerware/hugsql#39]
A thing just happened to me where I was writing a query and started in the `.sql` file with:

```
-- :name
```

but I didn't know what I wanted to name my query yet, so I wrote out the query:

```
-- :name
select * from ...
...
```

and when I was satisfied with the query I reloaded my code, forgetting to go back and give the query a name. And the result was a `NullPointerException`. It's kind of a rare case, and didn't take me too long to figure out the problem, but it's a fairly vague error message.

If you are interested in a validation there I can make a patch, but I won't be offended if you aren't interested.

**Comment by csummers** [comment]
Good catch!  Thanks for the report!

I added a validation exception for this that dumps the corresponding SQL statement for context.  This will roll into the next release.
