### ISSUE TITLE
Calling stored procedures?

### ISSUE THREAD

**Issue by dealy663** [layerware/hugsql#43]
Hi

Is there a way to call Postgres stored functions with HugSQL?

In particular is there a way to make this type of call on a function that returns a value, or set of values, or has out parameters?

Thanks, Derek

**Comment by csummers** [comment]
The basic rule here is that you can do anything that the underlying `clojure.java.jdbc` library and the database-specific JDBC driver supports with HugSQL.  So, you should be able to create functions/procedures and then call those returning a value or a result set as part of a regular SQL SELECT statement where a single result set is returned.  This may be sufficient for your needs, however you'll likely run into issues with out parameters.

If you're really needing stored procedures support at the language level, you probably need to consider dropping down into Java interop with the Postgresql JDBC driver ([docs](https://jdbc.postgresql.org/documentation/head/callproc.html)).  You can likely do most of your SQL with HugSQL, and then create a few wrapper functions for things like multiple result sets (cursors)

**Comment by dealy663** [comment]
Yes, it is the out parameters that have been tripping me up. I'm sure that I can figure it out using interop to get to the regular jdbc call prepared functionality. Just was wondering if I was missing some easier way with HugSQL.

**Comment by csummers** [comment]
Yes, HugSQL is sort of at the mercy of what `clojure.java.jdbc` supports for now.

Here are the relevant `clojure.java.jdbc` JIRA issues, which may shed some light on what your issue:

[Support stored procedures with CallableStatement](http://dev.clojure.org/jira/browse/JDBC-48)

[Support multiple result sets?](http://dev.clojure.org/jira/browse/JDBC-64)
