### ISSUE TITLE
SQL's `AS` result will be lowercased could be a surprise.

### ISSUE THREAD

**Issue by chao787** [layerware/hugsql#48]
for ex: 
`SELECT id AS mixId FROM some_table` will give result 

```
[{:mixid 123}, {:mixid 124}, ...]
```

It is common to use lowercase in clojure symbol, but to compatible with SQL structure, IMHO, we should make sure the keyword is exactly same with the alias after `AS`.

**Comment by csummers** [comment]
This is actually not controlled by HugSQL directly, but by the underlying database library.  In `clojure.java.jdbc`, the default is to lower-case the returned column names.  See the [doc string for clojure.java.jdbc/query](https://clojure.github.io/java.jdbc/#clojure.java.jdbc/query)

You can use [HugSQL's pass-through options](http://www.hugsql.org/#using-advanced) to pass the `:identifiers identity` through to `clojure.java.jdbc/query` to change this behavior.

For what it's worth, I don't necessarily agree with 'clojure.java.jdbc`'s use of lower-case here.

**Comment by csummers** [comment]
Also, this is related to requests for transforming column names to change snake_case to kebab-case: 

Issue #21 
Issue #40 

It may be that an `:identifiers` pass-through option defined during the initial `def-db-fns` call will eventually be the solution to this.  I haven't quite decided if that will be the case.

**Comment by csummers** [comment]
Closing this for now since the original inquiry is related to the underlying library's surprising behavior.
