### ISSUE TITLE
Inserting a record key not working when using :i!.

### ISSUE THREAD

**Issue by wnederhof** [layerware/hugsql#49]
Using `hugsql 0.4.7` (through `conman 0.5.8`), I get the following error using `:i!` to get the insert id from a `MySQL` database insert:
```
Wrong number of args (2) passed to: jdbc/db-do-prepared-return-keys
```
Head of the stack trace:
```
clojure.lang.ArityException: Wrong number of args (2) passed to: jdbc/db-do-prepared-return-keys
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at hugsql.adapter.clojure_java_jdbc.HugsqlAdapterClojureJavaJdbc.execute(clojure_java_jdbc.clj:11)
	at hugsql.adapter$eval16389$fn__16390$G__16369__16395.invoke(adapter.clj:3)
	at hugsql.adapter$eval16389$fn__16390$G__16368__16401.invoke(adapter.clj:3)
	at clojure.lang.Var.invoke(Var.java:394)
	at hugsql.core$db_fn_STAR_$y__16710.doInvoke(core.clj:463)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at hugsql.core$db_fn_STAR_$y__16710.invoke(core.clj:453)
```
E.g.
```
-- :name insert-record! :i!
INSERT INTO records (id, name, value)
VALUES (NULL, :name, :value)
```

**Comment by csummers** [comment]
2 is a valid arity for `db-do-prepared-return-keys` in `clojure.java.jdbc` version `0.6.1`, which is the dependency in conman.  It is also valid in `clojure.java.jdbc`' version `0.5.8`, which is what HugSQL `0.4.7` currently pulls in.  So, this leads me to think that you must have an earlier version of `clojure.java.jdbc` sneaking in from somewhere.

Can you do a `lein deps :tree` to look at all of your dependencies?

**Comment by wnederhof** [comment]
After removing most of the irrelevant dependencies, this is the result:
```
 [conman "0.5.8"]
   [com.carouselapps/to-jdbc-uri "0.5.0"]
   [com.layerware/hugsql "0.4.7"]
     [com.layerware/hugsql-adapter-clojure-java-jdbc "0.4.7"]
     [com.layerware/hugsql-core "0.4.7"]
       [com.layerware/hugsql-adapter "0.4.7"]
   [com.zaxxer/HikariCP "2.4.6"]
     [org.slf4j/slf4j-api "1.7.16"]
   [hikari-cp "1.7.0"]
     [org.tobereplaced/lettercase "1.0.0"]
     [prismatic/schema "1.0.4"]
 [environ "1.0.2"]
 [mount "0.1.10"]
 [mysql/mysql-connector-java "5.1.38"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/java.jdbc "0.6.2-alpha2"]
 [org.clojure/tools.nrepl "0.2.12" :scope "test"]
```
I tried using multiple different versions of `jdbc` myself, including `0.5.8` and `0.4.7`, since I do not see it being referenced from elsewhere. Yet, the problem is still there.

**Comment by csummers** [comment]
Please provide the entire stack trace.

Also, maybe try a `lein clean` if you haven't already.

**Comment by csummers** [comment]
Hmm...I've been unable to recreate this issue creating a new luminus app with mysql and  `conman 0.5.8`, `hugsql 0.4.7`, `clojure.java.jdbc 0.6.1`, so I'm not sure what's different about your environment that might be causing this.

**Comment by wnederhof** [comment]
`lein clean` fixed the problem. I had used a very old version of the JDBC connector earlier, and forgot to run that command after changing the version number (I thought that restarting the repl would do that automatically as it also downloads missing dependencies, but apparently not). My apologies and thank you for your help!

**Comment by csummers** [comment]
Glad you figured it out!  I've been bit by similar old deps needing a `lein clean` before, so I feel your pain. :)
