### ISSUE TITLE
postgres date operation with a parameter type

### ISSUE THREAD

**Issue by garaud** [layerware/hugsql#51]
Hi,
This is more a question than an issue I think. I wrote a SQL query with a date operation, e.g.

```sql
SELECT item
  ,date
  ,value
FROM table AS X
JOIN (
  SELECT item,value,date
  FROM history
  WHERE date = :date - integer '7'
  ) AS H
ON X.item = H.item
```

When I called this with a `{:date yyyy-mm-dd}` (a joda.date type instance), I've got a:

```
PSQLException ERROR: operator does not exist: date = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 249  org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)
```

When I tried to explicit the type, such as `WHERE date = date :date - integer '7'`, I've got a:

```
PSQLException ERROR: syntax error at or near "$1"
  Position: 256  org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)
```

I would like to figure out why I've got these errors what I could do to fix them.

See also https://www.postgresql.org/docs/current/static/functions-datetime.html for different date operations.

Cheers,
Damien

**Comment by csummers** [comment]
Try specifying the type cast as

```WHERE date = :date::date - integer '7'``` (older pg type cast syntax)
OR
 ```WHERE date = cast(:date AS date) - integer '7'``` (SQL standard)

**Comment by garaud** [comment]
Thank you for your answer. I did the wrong way to cast. It was a SQL/PostgreSQL problem, not hugSQL. Great work by the way.
Best.
