### ISSUE TITLE
SQLite INSERT or IGNORE

### ISSUE THREAD

**Issue by JanVanRyswyck** [layerware/hugsql#60]
I'm using HugSQL with Luminus and SQLite as the database. I have the following query in a sql file:

-- :name get-current-aggregate-version :returning-execute :one
-- :doc retrieve the current version of an aggregate root
INSERT OR IGNORE INTO Aggregates VALUES (:aggregate-id, 0);
SELECT Version FROM Aggregates WHERE AggregateId = :aggregate-id

When I execute the query, I get the following error:
ArrayIndexOutOfBoundsException 1  org.sqlite.core.CorePreparedStatement.batch (CorePreparedStatement.java:110)

I'm probably doing something wrong, but as I'm rather new to HugSQL I have some difficulties in figuring this out. I might also try to execute the query first and the insert second (if the query yields an empty result). But I would rather try to understand what I'm doing wrong here. Many thanks in advance for the help.

**Comment by csummers** [comment]
@JanVanRyswyck HugSQL can only run a single SQL statement or query at a time, so you'll need to break these up into two separate queries.  You can, of course, create a wrapper function to call both of the HugSQL-created functions in succession.

**Comment by JanVanRyswyck** [comment]
Thank you. That seems to do the trick.
