### ISSUE TITLE
Value Maps

### ISSUE THREAD

**Issue by MafcoCinco** [layerware/hugsql#61]
Is there currently any support for Value Maps?  I do not see it in the documentation, but, based on my admittedly limited experience with HugSQL, seems like it should be possible to add as an adapter?  Is this correct?

The idea would be to be able to do something like this on an INSERT, for example:

```clojure
(characters/insert-characters
   db
   {:characters
      [{:name "Vizzini" :specialty "intelligence"}
       {:name "Fezzik" :specialty "strength"}
       {:name "Inigo Montoya" :specialty "swordmanship"}]})
```
It is not a huge deal, as it is relatively easy to transform the data into a Value list.  However, not having to know the order of columns in the database would be pretty helpful in preventing bugs as well as avoiding an extra transformation.

**Comment by juanjoLenero** [comment]
I support the idea since JSON from API clients is usually transformed into maps and while trivial, a conversion to value lists is still an extra step.

**Comment by csummers** [comment]
If you really want to jump through the hoops to build this kind of thing as a custom [HugSQL parameter type](https://www.hugsql.org/#param-types) or [HugSQL Clojure expression](https://www.hugsql.org/#using-expressions), you could do so.

However, in this case, I recommend knowing and using the underlying library that may already support this very thing.  For instance, [clojure.java.jdbc](http://clojure-doc.org/articles/ecosystem/java_jdbc/using_sql.html#contents) (used by default in HugSQL) has a [great API](http://clojure-doc.org/articles/ecosystem/java_jdbc/using_sql.html#inserting-data) for this kind of insert/update stuff.
