### ISSUE TITLE
Support for `:result-fn`

### ISSUE THREAD

**Issue by MafcoCinco** [layerware/hugsql#62]
Any plans to support a function for `:result` (possible `:result-fn`)?  You mention YeSQL's `result-set-fn` which is a little more flexible than the current implementation of `:result` in HugSQL.  Would be nice to push all result sets through a transformation function before returning them to the user.  This could allow correction of discrepancies between the data store and Clojure.

**Comment by iku000888** [comment]
This works for me, and should address such need, if I am understanding correctly

```
(some-hugsql-db-fn db-spec
                                     {:email email}
                                     {}
                                     {:identifiers ->kebab-case
                                      :result-set-fn first
                                      :row-fn do-something-with-each-row})
```

**Comment by MafcoCinco** [comment]
Sweet.  Thanks @iku000888!  I was not aware that this was a thing.  Definitely looks to be doing what I was looking for.

**Comment by iku000888** [comment]
@MafcoCinco My pleasure!

I guess it is worth mentioning that the snippet I pasted relies on options for the underlying clojure.java.jdbc and dunno what to do if one needs to deal with some other jdbc lib (i.e. clojure.jdbc).
