### ISSUE TITLE
Question: parameters within single-quoted strings

### ISSUE THREAD

**Issue by pauldorman** [layerware/hugsql#64]
I'm using the [SQL4Jira](https://kintosoft.atlassian.net/wiki/display/SFJ/SQL+for+JIRA+Driver) driver which has a slightly odd query syntax where Jira's  JQL must be included within some queries.

The syntax for JQL injection is to include it within a single-quoted string, e.g.
```
...
issuecustomfields cf ON cf.issueid=i.id
WHERE
    jql='project = ":name" order by updated DESC'
```
I tried a number of approaches to have my :name parameter picked up by def-db-fns, but in the end I resorted to a Clojure expression:

```
...
issuecustomfields cf ON cf.issueid=i.id
WHERE
--~ (str "jql='project = \"" (:name params) "\" ORDER BY updated DESC'")
```

While this works, it would be much easier if I could tell HugSQL to look for parameters within single-quoted strings. I know this is a pretty obscure use-case, but is there a way to accomplish this that I may have overlooked?

**Comment by csummers** [comment]
Well, I feel for ya, but I think I'm going to leave this one as is.  You've actually come up with a fine solution: clojure expressions allow you to "break out" of the normal parsing pattern for cases like this one.
