### ISSUE TITLE
Inserting nil into an Integer column throws exception

### ISSUE THREAD

**Issue by bostonaholic** [layerware/hugsql#69]
I have a column that is of type `integer`, using postgresql. When I try to insert a `nil` into that column, it throws an exception.

```
-- :name insert-thing
INSERT INTO things (title, body, a_number)
VALUES (:title, :body, :a-number)
RETURNING *;
```

Here's what the generated `-sqlvec` looks like

```
[INSERT INTO things(title, body, a_number) VALUES (?, ?, ?); title, body, nil]
```

And the exception

```
org.postgresql.util.PSQLException: ERROR: column "a_number" is of type integer but expression is of type text
  Hint: You will need to rewrite or cast the expression.
...
```

**Comment by bostonaholic** [comment]
I have a workaround that works in the meantime.

I can cast the nullable integer columns.

```
INSERT INTO things (title, body, a_number)
VALUES (:title, :body, :a-number::integer)
RETURNING *;
```

**Comment by csummers** [comment]
Your postgresql exception seems to indicate that a string (type text) was passed in as a parameter.  You might look at your postgresql log to see what was actually being passed to the database.

**Comment by bostonaholic** [comment]
@csummers `nil` is being sent to the hugsql function.

**Comment by csummers** [comment]
Are you still seeing this issue?

Replacing the `nil` in the SQL actually happens in the underlying database library.  It should put `NULL` for nil values before sending along to the database.

Can you provide the underlying database library and version you are using?  `clojure.java.jdbc` or `clojure.jdbc` or something else?  Also, can you provide the version of the postgresql jdbc library you are using?

**Comment by bostonaholic** [comment]
I am no longer working on that project (previous employer). I will try to create a minimal test case to isolate the issue.
