### ISSUE TITLE
Oracle SQL optimizer hints are dropped

### ISSUE THREAD

**Issue by alvinfrancis** [layerware/hugsql#71]
https://docs.oracle.com/cd/B19306_01/server.102/b14211/hintsref.htm#i8327

Oracle SQL has a mechanism that allows adding hints to a query to change it's execution plan.  These hints are in the form of a comment following the `SELECT` keyword.  

Example:
```sql
SELECT /*+ FIRST_ROWS(n) */
FROM some_table
```

It looks like hugsql parsing is dropping all comments save for hugsql expressions and headers.  This can be a surprising change in terms of the performance of a query since the developer would expect the query to run would be the same as he wrote for oracle.  The parser needs to allow comments of the form `/*+ ... */`, to keep these optimizer hints.

**Comment by Michieljoris** [comment]
Ran into this issue as well. Great it's been fixed and merged. If a new release could be pushed it would be really helpful.
