### ISSUE TITLE
Hugsql-generated functions lack file/line metadata

### ISSUE THREAD

**Issue by technomancy** [layerware/hugsql#77]
The biggest complaint I've heard from people I've talked to who use hugsql is that jump-to-definition functions stop working as soon as they hit a hugsql-generated function.

It looks like hugsql uses a `source-logging-push-back-reader` which is capable of tracking line numbers and filenames. Attaching this metadata to the vars created by hugsql would allow existing tooling to be able to jump straight to the `.sql` files from which they are defined.

**Comment by csummers** [comment]
Released in version 0.4.9.  Thanks!
