### ISSUE TITLE
No valid hugsql header found error only when aot-ing

### ISSUE THREAD

**Issue by iku000888** [layerware/hugsql#81]
I have the following in a .sql file in one of my internal modules, which I consume from (def-db-fns)

While working at the repl things are fine, but when I aot(leiningen) it from a project depending on it I got an error saying it does not have a valid hugsql header.

I worked around the issue by using def-db-fns-from-string instead.

```
-- :name enable-unicode! :! :n
SET NAMES utf8 COLLATE utf8_bin;
```

**Comment by csummers** [comment]
Closing this for now.  If this is still an issue and you can provide a reproducible example, please re-open.  Thanks!
