### ISSUE TITLE
Add basic arglists metadata to generated fns

### ISSUE THREAD

**Issue by j0ni** [layerware/hugsql#88]
the `:arglists` function metadata is used by mocking frameworks such as [CircleCi's bond](https://github.com/circleci/bond/blob/master/src/bond/james.cljc#L84) toolkit to determine whether the correct number of arguments has been supplied at runtime.

One could argue that we shouldn't be mocking generated functions (in fact I would argue that), but code exists which does, and I don't see any particular reason to avoid supporting that use case.

**Comment by csummers** [comment]
e5e4f928b612ec27b997b097ff7c1d9c63a69985 adds this and it will ship in `0.5.0` soon.

**Comment by csummers** [comment]
This is released in `0.5.0`.
