### ISSUE TITLE
Allow adapters to override exceptions

### ISSUE THREAD

**Issue by Skinney** [layerware/hugsql#9]
It would be great if hugsql allowed adapters to catch exceptions. The jdbc-adapters can simply just re-throw the exceptions, but my async adapter could return the exception on a channel, which would make it consistent with db-errors.

**Comment by csummers** [comment]
So, I'm interested in possibly getting this into 0.3.0.  Could you provide a rough example of what you're looking for?  For my own understanding, is this not something that each individual adapter could handle within its implementation?  Or, do we need a unified HugsqlException for you to catch?

I'm open to it--just a little fuzzy on the details of what's needed.  Thanks!

**Comment by Skinney** [comment]
Essentially, I want an `on-exception` function on the HugsqlAdapter so that I can control how exceptions are thrown (example below).

The reason for this is that throwing an exception inside a go-block is impossible to catch outside the go-block. The postgres-async library (and many others) therefore returns exceptions on a channel. Currently, if hugsql throws an exception, I cannot catch it and return it on a channel. Because of that, calling a hugsql fn with my async-adapter can both throw an exception and return an exception, and I'd like to make that consistent.

```
(defprotocol HugsqlAdapter
  "Hugsql Adapter Protocol"

  (execute [this db sqlvec options]
    "Execute SQL/DDL/DML statement")

  (query [this db sqlvec options]
    "Query SQL statement (expecting result set)")

  (result-one [this result options]
    "Result: returns one hashmap record")

  (result-many [this result options]
    "Result: returns vector of hashmap records")

  (result-affected [this result options]
    "Result: returns integer of affected rows/records")

  (result-raw [this result options]
    "Result: returns raw result, untouched")

  (on-exception [this exception]
    ;; regular adapters can just re-throw the exception
    (throw exception)
    ;; my adapter could stick it on a channel
    (go exception))
```

**Comment by csummers** [comment]
This is now in as of the 0.3.0 release.

Please confirm that it will work for your needs.  I'll close after you confirm.

Among other ways, you should be able to trigger an exception by not providing the expected parameter data to your function calls.

**Comment by Skinney** [comment]
I can't trigger an exception.

```clojure
    (<!! (go
           (println (<! (create-table db)))
           (println (<! (insert-num db {:name "Robin"})))
           (println (<! (get-nums db)))
           (println (<! (get-num db {:num num :name "Robin"})))
           (close-db! db)))
```

Removing :num from the last get-num call does not trigger an exception.

**Comment by csummers** [comment]
Hmm.  We might need a full example to track this down.  If you change back to the default adapter and run the same functions outside of the go block, does it trigger an exception?

**Comment by Skinney** [comment]
Will check later. Meanwhile, here is the full code that I use for testing:

```sql
-- :name create-table :!
CREATE TABLE IF NOT EXISTS numbers (
       num bigint,
       name text
);

-- :name insert-num :!
INSERT INTO numbers (num, name)
VALUES (:v:num, :v:name);

-- :name get-nums :? :*
SELECT *
FROM numbers;

-- :name get-num :? :1
SELECT *
FROM numbers
WHERE num = :v:num
AND name = :v:name;
```

```clojure
(ns core
  (:require [postgres.async :refer :all]
            [hugsql.core :as hugsql]
            [hugsql.adapter.postgres-async :as ps-adapter]
            [clojure.core.async :refer [go <! <!!]]))

(hugsql/def-db-fns "fns.sql")

(defn -main []
  (let [db (open-db {:hostname "localhost"
                     :port 5432 ; default
                     :database "hugsql"
                     :username "skinney"
                     :password "password"
                     :pool-size 2})
        num (System/currentTimeMillis)]
    (hugsql/set-adapter! (ps-adapter/hugsql-adapter-postgres-async))
    (<!! (go
           (println (<! (create-table db)))
           (println (<! (insert-num db {:num num :name "Robin"})))
           (println (<! (get-nums db)))
           (println (<! (get-num db {:num num :name "Robin"})))
           (close-db! db)))))
```

```clj
(defproject skinney/hugsql-async-test "0.1.0-SNAPSHOT"
  :main core
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/core.async "0.2.374"]
                 [com.layerware/hugsql-core "0.3.0"]
                 [skinney/hugsql-adapter-postgres-async "0.3.0"]
                 [alaisi/postgres.async "0.6.0"]])
```

**Comment by csummers** [comment]
I'm just circling back on this.  I definitely get the exception with the other adapter set.  And, upon inspecting the exception in your adapter I can see that it is actually there within `on-exception` (I can prn it).  It does seem to get lost after it's put on that channel in `on-exception`.

**Comment by Skinney** [comment]
Sorry. I completely forgot about this.
I've confirmed that this is a issue with my library, so I'm closing this issue.

**Comment by Skinney** [comment]
On closer inspection. It seems that the result of `on-exception` isn't returned to the user.

**Comment by Skinney** [comment]
Hmm. Even though on-exception is called, it still seems to perform the actual query. If I remove `:num` from the insert, and later do a retrieve, it will return {:num nil, :name "Robin"}.

I haven't looked through your code in a while, but based on what is happening, it would seem that you depend on the fact that `on-exception` will throw.

**Comment by csummers** [comment]
Yes, I think that's it! Upon error in `validate-parameters!` I was unnecessarily calling `on-exception` early on the adapter, but then later trying to catch any exception when the user-defined functions run.

I'll test to make sure that's it and push out a 0.3.1 later today with the fix.

**Comment by csummers** [comment]
0.3.1 is released with this fix.  I'll let you confirm and close.

**Comment by Skinney** [comment]
Confirmed
