### ISSUE TITLE
hugsql adapter for ClickHouse

### ISSUE THREAD

**Issue by anthonyshull** [layerware/hugsql#91]
We wrote a hugsql adapter for [ClickHouse](https://clickhouse.yandex/)

https://clojars.org/us.2da/hugsql-adapter-clickhouse-native-jdbc
https://github.com/2DA-Analytics/hugsql-clickhouse

**Comment by csummers** [comment]
Excellent.  I'll add a link to the docs in the next release.

**Comment by csummers** [comment]
264eb59e18a1e250770595fdb519756c64eb7575 adds this and it will ship in `0.5.0` soon.

**Comment by csummers** [comment]
This is released in `0.5.0`.
