### ISSUE TITLE
Adapter for next-jdbc

### ISSUE THREAD

**Issue by nikolap** [layerware/hugsql#96]
Here's a working adapter for [next-jdbc](https://github.com/seancorfield/next-jdbc.git): https://gitlab.com/nikperic/hugsql-next-jdbc

Once next-jdbc gets out of alpha, I'd encourage simply merging it into hugsql itself, but, ultimately, that decision is yours!

**Comment by seancorfield** [comment]
Thanks for creating this @nikolap ! I'm preparing for Beta 1 and just made the last breaking change: renaming `reducible!` to `plan` -- there will be no further breaking changes. I have decided to keep the group/artifact ID and the namespace names the same -- and not move `next.jdbc` into Contrib.

**Comment by csummers** [comment]
This is great, and, yes, I've been keeping my eye on next.jdbc for a while and looking forward to the stable release.  I probably will want to ship HugSQL directly with this adapter.  Since this is on gitlab, would you like to open a PR on github?  Or, would you mind if I copy this directly in?

**Comment by nikolap** [comment]
I can throw up a PR for you or you can copy it in -- whatever's easier for you.

Would you like to release it with the Beta 1 version or wait until a stable release?

**Comment by seancorfield** [comment]
FWIW, the adapter isn't affected by the alpha -> beta change since the adapter does not use `reducible!` (which is being renamed) -- so it is "stable" as it stands.

One thing to be aware of is the change in the default from lower-case, unqualified column names to as-is, qualified column names. I'm not sure whether you want to take that into account somehow?

**Comment by nikolap** [comment]
@csummers next.jdbc is 1.0.0! Feel free to copy in the adapter

**Comment by seancorfield** [comment]
Let me know if you have any questions about `next.jdbc`. 

Regarding the column name change above, you could allow `:builder-fn` to be passed through as an option (maybe -- I don't know how much control over adapter options HugSQL provides?) and default it to `next.jdbc.result-set/as-unqualified-lower-maps` if you wanted to preserve the default naming strategy, vis-a-vis `clojure.java.jdbc`.

**Comment by vinurs** [comment]
when this will be merged?

**Comment by csummers** [comment]
7458af931aa04935718621319d7be1e0a6ae3348 and 422a138ad3f6fde2c036385f95ccd0078069d093 bring in support for `next.jdbc` and will ship with an upcoming 0.5.0 release.

@nikolap Thank you for the PR!  @seancorfield Thank you for `next.jdbc`.

I decided to make the default `:builder-fn` option in the adapter use `next.jdbc.result-set/as-unqualified-lower-maps` to preserve naming compatibility and create fewer surprises for users who are coming from `clojure.java.jdbc`--which is probably the bulk of users :smile:.

@nikolap, I appreciate your adapter providing an arity for `default-command-options` to make it easy for users to set a different `:builder-fn`.

**Comment by csummers** [comment]
This is released in `0.5.0`.
