### ISSUE TITLE
Postgres enum types and tuple inserts

### ISSUE THREAD

**Issue by MafcoCinco** [layerware/hugsql#97]
From the documentation, if I want to insert multiple rows, it can be done like so:

```sql
-- :name insert-characters :! :n
-- :doc Insert multiple characters with :tuple* parameter type
insert into characters (name, specialty)
values :tuple*:characters
```

HugSQL expects to receive a map containing a `:characters` key with a value of a vector of vectors, each child vector containing 2 values, the name and the specialty.

Now, suppose that I'm inserting into a Postgres DB and the `specialty` column is not a string but instead a PG enum type that is defined in the database called `specialty_enum`.  If I was doing a single row insert, I would add something like this to my HugSQL SQL: `:specialty::specialty_enum`.  This would cast the string value to the enumeration and successfully insert into PG, assuming the string contained a valid enum value.

However, the multi-row insert does not seem to allow the "casting" syntax.  I attempted to do this and received the following error:

```
PSQLException ERROR: column "specialty" is of type specialty_enum but expression is of type character varying
  Hint: You will need to rewrite or cast the expression
```

I would like to know if this is possible and, if so, what is the proper syntax both on the SQL side as well as any (possibly necessary) formatting of the values I am attempting to insert.

Thanks for your help!

**Comment by csummers** [comment]
This is possible with a little work in a Clojure Expression.  You'll have to generate the intended parameter placeholders with the casting appended.

Here's a similar issue (and my answer) from stackoverflow that should point you in the right direction:  https://stackoverflow.com/questions/51546003/casting-multiple-values-in-hugsql-or-yesql-with-postgres/51600434#51600434

**Comment by MafcoCinco** [comment]
Thanks @csummers! That is exactly what I needed.
