### ISSUE TITLE
Clojure expressions in queries file crashes repl

### ISSUE THREAD

**Issue by bolivier** [layerware/hugsql#98]
```
$ java -version
java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

```
$ lein --version
Leiningen 2.9.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM
```

OS: MacOS 10.14.5 Mojave

I'm also using Emacs and CIDER.

Any instance of clojure expressions in my `queries.sql` file causes the file to crash.  I'm pretty new to Clojure, so I'm probably screwing something up, but I cannot figure out what it might be. 

I reproduced it with a new app by doing 

`$ lein new luminus tester +postgres`

create a db, run migrate, and everything works fine.

I added the simplest case I could imagine, reading the docs, 

```
insert into users(
--~ "id"
...other fields
) values (
...all fields
);
```

When I try to load the new definitions, I get 

`clojure.lang.Symbol cannot be cast to clojure.lang.Namespace`

```
ERROR: Unhandled REPL handler exception processing message {:nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/options {:right-margin 80}, :op stacktrace, :session 00a34a9b-3eed-495f-b28c-f2a463c3a858, :id 12}
```

**Comment by csummers** [comment]
There's really not enough here for me to duplicate your issue.  Did you solve your problem?
